---
- name: _CONDITIONALS
  hosts: cortez magellan
  remote_user: admin
  become: yes

  tasks: 
  - name: "CHANGED_WHEN > THEN"
    command: getenforce
    register: sestatus
    changed_when: false

  - name: DO SOMETHING IF FILE EXISTS
    stat:
      path: /etc/os-release
    register: p
    
  - debug: msg="Path exists and is a directory"
    when: p.stat.isdir is defined and p.stat.isdir
