
---
- name: HOW TO DO STUFF WITH FILES
  hosts: cortez
  remote_user: admin
  become: yes

- name: Create a file
  tasks:
    - name: file created at tmp, with varaible as input
      vars:
        - fileName: file-touched-by-ansible
      file:
        path: /tmp/{{ fileName }}.txt
        state: touch
        mode: 0644
