---
- name: HOW TO DO STUFF WITH FILES
  hosts: cortez magellan
  remote_user: admin
  become: yes
  vars:
    fileName: file-touched-by-ansible

  tasks:
    - name: Create a file
      file:
        path: /tmp/{{ fileName }}.txt
        state: touch
        mode: 0644

    - name: edit a file
      lineinfile:
        path: /tmp/{{ fileName }}.txt
        line: added a single line

    - name: add another line     
      lineinfile:
        path: /tmp/{{ fileName }}.txt
        line: added a single line

    - name: blockedit a file
      blockinfile:
        path: /tmp/{{ fileName }}.txt
        block: |
          if [ -f `which powerline-daemon` ]; then
            powerline-daemon -q
            POWERLINE_BASH_CONTINUATION=1
            POWERLINE_BASH_SELECT=1
            . /usr/share/powerline/bash/powerline.sh
          fi

    - name: Copy a [remote] file to a [remote] destination
      copy:
        remote_src: yes
        backup: yes
        src: /tmp/{{ fileName }}.txt
        dest: /usr/local/bin/{{ fileName }}.txt
        mode: 0755

    - name: Copy a [local] file to a [remote] destination
      copy:
        src: /src/unit-file.service
        dest: /tmp/unit-file.service
        validate: /usr/bin/systemd-analyze verify %s


    - name: Copy a [local] file to a [remote] destination, and validate it
      copy:
        src: /src/wall-message.txt
        dest: /tmp/wall-message.txt

    # optional but possible:
    #   owner: "{{userId}}"
    #   group: "{{groupId}}"

    - name: "remove a file > file created in /tmp will be removed"
      file:
        path: /tmp/{{ fileName }}.txt
        state: absent

    - name: Download a programme
      unarchive:
        src: "https://github.com/prometheus/alertmanager/releases/download/v{{ version }}/alertmanager-{{ version }}.linux-amd64.tar.gz"
        dest: /tmp/
        remote_src: yes

    - name: Copy alertmanager executable to bin
      copy:
        src: "/tmp/alertmanager-{{ version }}.linux-amd64/alertmanager"
        dest: "/usr/local/bin/alertmanager"
        owner: "{{userId}}"
        group: "{{groupId}}"
        remote_src: yes
        mode: 0755
    - name: Delete alertmanager tmp folder
      file:
        path: '/tmp/alertmanager-{{ version }}.linux-amd64'
        state: absent