---
- name: test the getting of info
  hosts: localhost
  become: yes

  tasks:
  - name: get release info
    slurp:
      src: /etc/os-release
    register: release

  - name: Print Release Information
    debug: 
      msg: "{{ release['content'] | b64decode }}"
