---
- name: EXPLAINER FOR DEBUGGING / MESSAGE FROM SYSTEMS - HOW TO
  hosts: magellan
  remote_user: admin
  become: yes

  tasks:
    - name: "do something: make a file"
      file:
        path: /tmp/file-made-with-debugging-playbook.on-{{ ansible_facts['nodename'] }}.txt
        state: touch
        mode: 0644
      tags: something

    - debug: 
        var: ansible_facts.distribution
    - debug:    
        var: ansible_facts.selinux.status
    - debug:    
        var: ansible_facts['selinux']['status']

    # [-----------------------------------------]
    # as is known, one may disable the fact gathering by adding to playbook
    #   - hosts: host_everything_is_known_about
    #     gather_facts: no
    # (may increase scaling factor when managing a large number of remotes)

    # [-----------------------------------------]
    # it is possible to gather local facts

    - name: "create a local ansible preferences file"
      file:
        path: /etc/ansible/facts.d
        state: directory

    - name: "create a local ansible preferences file"
      file:
        path: /etc/ansible/facts.d
        state: directory

    - name: "how do them conditionals work now?"     
      file:
        path: /etc/ansible/facts.d/preferences.fact
        state: touch
        mode: 0644
      tags: creating_local_facts

    - name: edit that local preferences file
      blockinfile:
        path: /etc/ansible/facts.d/preferences.fact
        block: |
          [motd]
          mariadb: op
          postgresql: op
          zabbix: test
          [{{ ansible_facts['nodename'] }}]
          testytest: test
      tags: creating_local_facts
      
    - name: feed back that info
      debug:
        msg: ""

    - name: register file contents
      slurp:
        src: /etc/os-release
      register: release

    - name: Print Release Information
      debug: 
        msg: "{{ release['content'] | b64decode }}"        
