
---
- name: MANAGING USERS INFO
  hosts: cortez magellan
  become: yes

  tasks:
    - name: Creating user group
      group: name="{{groupId}}"
      become: true

    - name: Creating a nologin system user
      user:
        name: "{{userId}}"
        group: "{{groupId}}"
        system: yes
        shell: "/sbin/nologin"
        comment: "{{userId}} nologin User"
        createhome: "no"
        state: present