---
# ansible provides 16! different places from which it reads
# runtime variables
# vars_prompt overrides them all

# there are 16!! var fields / locations that ansible reads from. it uses whatever it finds first
# so if default dir is /home/admin/apps/ansible -> this directory can contain a config file that applies (and only that?)

# [-----------------------------------------]
# vars_prompt overrides them all

- name: EXPLAINER FOR VARIABLES - HOW TO
  hosts: cortez
  become: yes

  vars_prompt:
  - name: username
    prompt: What is a Username (fist initial lastname i.e. "George Allen" = gallen)?
  - name: password
    prompt: What is a password?

  tasks:
  - name: create a new user
    user: name={{ username }}
          state=present
          groups="geoclue"
          password={{ password }}
  - name: remove the user again
    user: name={{ username }}
          state=absent
          groups="geoclue"
          password={{ password }}   
          

# [-----------------------------------------]
# ansible-playbook {this_file}.yml --extra-vars="fileName=DEMOFILE" --ask-become-pass
# pass an extra var that has been defined in the yaml
# yaml looks like this:
  - name: make a file, using a command line passed variable
    file: 
      path: /tmp/{{ fileName }}.txt
      state: touch
      mode: 0644     
          