- name: different stuffs
  hosts: localhost
  become: yes

  tasks:
    # edit dconf module, enable, then disable
    - name: Enable Night Light
      dconf:
        key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
        value: true
    - name: Set Night Light Temperature
      dconf:
        key: /org/gnome/settings-daemon/plugins/color/night-light-temperature
        value: uint32 5500
    - name: disable Night Light again
      dconf:
        key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
        value: false


