---
- name: different stuffs
  hosts: localhost
  become: yes

  tasks:
# after update maybe ->
  - name: Update and restart ssh if it is updated
    dnf:
      name: "httpd"
      state: latest
    notify:
    - name: Restart Apache
    handlers:
    - name: Restart Apache
      service:
        name: httpd
        state: restarted      

# Create a file
  - name: file created at tmp, with varaible as input
    vars:
    - fileName: file-touched-by-ansible
    file: 
      path: /tmp/{{ fileName }}.txt
      state: touch
      mode: 0644        

# edit dconf module, enable, then disable
  - name: Enable Night Light
    dconf:
      key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
      value: true
  - name: Set Night Light Temperature
    dconf:
      key: /org/gnome/settings-daemon/plugins/color/night-light-temperature
      value: uint32 5500    
  - name: disable Night Light again    
    dconf:
      key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
      value: false  

  - name: Upgrade in the future
    command: echo "success"
    when: '"VERSION_ID=28" in fedora.content|b64decode' 
  - name: file created at tmp, with varaible as input
    when: '"VERSION_ID=28" in fedora.content|b64decode' 
    vars:
    - fileName: file-touched-by-ansible
    file: 
      path: /tmp/{{ fileName }}.txt
      state: touch
      mode: 0644        

  - name: get version info 
    command: getenforce
    register: VersionInfo
    changed_when: false      

