---
- name: remote check of Geoserver
  hosts: geo-osm-se
  remote_user: optitool
  become: yes
  tasks:
  - name: Upgrade all packages to the latest version
    apt:
      name: "*"
      state: latest