---
- name: test the getting of info
  hosts: cortez magellan dortmunder
  become: yes

  tasks:
  - name: get release info
    slurp:
      src: /etc/os-release
    register: fedora

  - name: Print Release Information
    debug: 
      msg: "{{ fedora['content'] | b64decode }}"
