---
- name: Upgrade Fedora Major Version
  hosts: localhost
  become: yes

  # query which version to install
  # maybe put this elsewehere, or simply edit in this file, i dont know
  vars_prompt:
  - name: version
    prompt: Which Version should we upgrade to?

  tasks:
    # first we install the plugin
  - name: Install the DNF plugin
    dnf:
      name: dnf-plugin-system-upgrade
      state: latest  
  
  # this must be solved differently, need to check when i have network 
  - name: Update software and back up your system
    dnf: 
      name: dnf upgrade --refresh

  - name: Start the update with the download
    dnf:
      name: system-upgrade download --releasever={{ version }}

  - name: reboot and upgrade
    dnf:
      name: system-upgrade reboot
