---
- name: Upgrade Fedora Major Version
  hosts: cortez
  become: yes

  tasks:
  - name: Install the DNF plugin
    dnf:
      name: dnf-plugin-system-upgrade
      state: latest  
  
  - name: Update software and back up your system
    shell: /usr/bin/dnf upgrade --refresh -y
   # warn: False

  - name: "Start the update with the download of packages"
    shell: /usr/bin/dnf system-upgrade download --allowerasing --assumeyes --releasever=29 

  - name: "wait for ssh to go down"
    local_action: wait_for host="{{ ansible_fqdn }}" port=22 state=stopped 

  - name: "Trigger the upgrade process"
    shell: sudo dnf system-upgrade reboot
