---
- name: Update the system to the latest versions
  hosts: dns
  remote_user: Administrator
  become: yes

  tasks:
  - name: get version info 
    command: getenforce
    register: VersionInfo
    changed_when: false

  - name: upgrade all packages
    dnf:
      name: "*"
      state: latest