---
- name: Setup Fedora Workstation with stuffs
  hosts: localhost
  become: yes

  vars:
    local_user: admin

  tasks:
  - name: Add Repository for Sublime Text
    yum_repository:
      name: sublime-text
      description: Sublime Text - x86_64 - Stable
      baseurl: https://download.sublimetext.com/rpm/stable/x86_64
      gpgkey: https://download.sublimetext.com/sublimehq-rpm-pub.gpg
      gpgcheck: yes

  - name: Update all software on system to current latest 
    dnf:
      name: "*"
      state: latest


  - include: "{{ playbook_dir }}/setup-workstation-tasks/defaults.yml"
  - include: "{{ playbook_dir }}/setup-workstation-tasks/gnome.yml"
  - include: "{{ playbook_dir }}/setup-workstation-tasks/vscode.yml"
  - include: "{{ playbook_dir }}/setup-workstation-tasks/sqlwb.yml"
  - include: "{{ playbook_dir }}/setup-workstation-tasks/pycharm.yml"


  - name: Install all that cool but obscure stuff
    dnf: 
      name: ['dstat', 'slurm', 'screen', 'dtach', 'powertop', 'atop', 'glances', 'mtr', 'iftop', 'nethogs']

  - name: Install database (client) software
    dnf: 
      name: ['sequeler', 'postgresql']

  - name: Install Python Environment 
    dnf: 
      name: ['python3', 'python3-mypy']
      
  - name: Install Productivity software
    dnf: 
      name: ['chromium', 'firefox', 'calibre']


  - name: Install Sublime Text
    dnf: 
      name: sublime-text
      state: latest

  - name: Install PowerLine
    dnf: 
      name: ['powerline', 'powerline-fonts']

  - name: Allow editing on an SELinux enforced system
    dnf:
      name: libselinux-python
      state: latest

  - name: "download script for custom bashrc, profile"
    get_url:
      url: "https://raw.githubusercontent.com/rogrwhitakr/northern-lights/master/script/setup-profile-on-new-box.bash"
      dest: "/home/{{ local_user }}/profile-setup.bash"
      mode: 0740
      owner: "{{ local_user }}"
      group: "{{ local_user }}"

  - name: Run the script
    become_user: "{{ local_user }}"
    script: "/home/{{ local_user }}/profile-setup.bash"
    args:
      executable: /usr/bin/bash
      creates: "/home/{{ local_user }}/.bashrc.d"


  - name: edit .bashrc to enable powerline usage
    blockinfile:
      path: /home/{{ local_user }}/.bashrc
      block: |
        if [ -f `which powerline-daemon` ]; then
          powerline-daemon -q
          POWERLINE_BASH_CONTINUATION=1
          POWERLINE_BASH_SELECT=1
          . /usr/share/powerline/bash/powerline.sh
        fi
