
---
- name: Update the system to the latest version
  hosts: cortez
  remote_user: admin
  become: yes

  tasks:
  - name: update all packages
    dnf:
      name: "*"
      state: latest

  - name: get release info
    slurp:
      src: /etc/os-release
    register: fedora
  - name: Upgrade in the future
    command: echo "success"
    when: '"VERSION_ID=28" in fedora.content|b64decode' 
  - name: file created at tmp, with varaible as input
    when: '"VERSION_ID=28" in fedora.content|b64decode' 
    vars:
    - fileName: file-touched-by-ansible
    file: 
      path: /tmp/{{ fileName }}.txt
      state: touch
      mode: 0644        

  - name: get version info 
    command: getenforce
    register: VersionInfo
    changed_when: false      

  - name: Install basic software
    dnf: name={{item}} state=present
    with_items:
    - nano
    - python3
    - python

  - name: Install monitoring software
    dnf: name={{item}} state=present
    with_items:
    - htop
    - sysstat
    - iotop
    - python