---
- name: Setup Fedora Workstation with stuffs
  hosts: localhost
  remote_user: benno
  become: yes

  tasks:
  - name: Add Repository for Microsoft VS CODE
    yum_repository:
      name: code
      description: Visual Studio Code
      baseurl: https://packages.microsoft.com/yumrepos/vscode
      gpgkey: https://packages.microsoft.com/keys/microsoft.asc
      gpgcheck: yes

  - name: Add Repository for Sublime Text
    yum_repository:
      name: sublime-text
      description: Sublime Text - x86_64 - Stable
      baseurl: https://download.sublimetext.com/rpm/stable/x86_64
      gpgkey: https://download.sublimetext.com/sublimehq-rpm-pub.gpg
      gpgcheck: yes

  - name: Update all software on system to current latest 
    dnf:
      name: "*"
      state: latest

  - name: Install basic software
    dnf: name={{item}} state=present
    with_items:
    - htop
    - nmap
    - nano

  - name: Install system / analytics software
    dnf: name={{item}} state=present
    with_items:
    - dconf-editor
    - firewalld
    - wireshark

  - name: Allow editing on an SELinux enforced system
    dnf:
      name: libselinux-python
      state: latest
      
  - name: Update GNOME softwares
    dnf: name={{item}} state=present
    with_items:
    - gnome-tweak-tool
    - gnome-todo
    - gnome-music

  - name: Remove unwanted default packages 
    dnf: name={{item}} state=absent
    with_items:
      - rhythmbox
      - shotwell
      - builder

  - name: Install Productivity software
    dnf: name={{item}} state=present
    with_items:
    - chromium
    - firefox
    - calibre

  - name: Install Powerline CLI 
    dnf: name={{item}} state=present
    with_items:
    - powerline 
    - powerline-fonts

  - name: Install visual studio code
    dnf: 
      name: code
      state: latest

  - name: Install Sublime Text
    dnf: 
      name: sublime-text
      state: latest

  - name: Install PowerLine
    dnf: name={{item}} state=present
    with_items:
    - powerline
    - powerline-fonts

  - name: edit .bashrc to enable powerline usage

    blockinfile:
      path: /home/benno/.bashrc
      block: |
        if [ -f `which powerline-daemon` ]; then
          powerline-daemon -q
          POWERLINE_BASH_CONTINUATION=1
          POWERLINE_BASH_SELECT=1
          . /usr/share/powerline/bash/powerline.sh
        fi