---
- name: Shutdown a remote computer
  gather_facts: no
  hosts: "{{ host }}"
  remote_user: admin
  become: yes

  tasks:
  - name: user-instigated shutdown
    command: /sbin/shutdown -h now
    sudo: yes

  - name: wait go down
    local_action: wait_for host={{ ansible_ssh_host }} port=22 state=stopped