# tasks file for pycharm
---
- name: Setup Fedora Workstation with stuffs
  hosts: localhost
  become: yes
  tasks:
  - name: Create a temporary download directory
    file:
      path: /tmp/pycharm
      state: directory
    register: pycharm_tmp_dir

  - name: Get releases
    uri:
      url: https://data.services.jetbrains.com/products/releases?code=PCC&type=release
      method: GET
    register: json_response

  - name: Print Information
    debug:
      msg: "downloading from {{ json_response.json.PCC[1].downloads.linux.link }}"

  - name: Print Information to file
    file:
      path: json_response.json
      state: touch
      mode: 0644

  - name: Print Information to file (cont) 
    blockinfile:
      path: json_response.json
      block: |
        "{{ json_response }}"

  - name: Download latest PyCharm Community Edition
    get_url:
      url: "{{ json_response.json.PCC[0].downloads.linux.link }}"
      dest: "{{ pycharm_tmp_dir.path }}/pycharm.tar.gz"
    register: got_charm

# https://download.jetbrains.com/product?code=PCC&latest&distribution=linux
# shoudl work also....

  - name: download Info
    debug: 
      msg: "PyCharm was successfully downloaded"
    when: got_charm.changed

  - name: Unpack install archive
    unarchive:
      src: "{{ pycharm_tmp_dir.path }}/pycharm.tar.gz"
      dest: /home/admin
      list_files: yes
    register: pycharm_unarchive

  - name: Install PyCharm
    command: "./{{ pycharm_unarchive.files | first }}"