# tasks file for pycharm
---
- name: Create a temporary download directory
  file:
    path: /tmp/pycharm
    state: directory
  register: pycharm_tmp_dir

- name: Get releases
  uri:
    url: https://data.services.jetbrains.com/products/releases?code=PCC&type=release
    method: GET
  register: json_response

- name: Download latest PyCharm Community Edition
  get_url:
    url: "{{ json_response.json.PCC[0].downloads.linux.link }}"
    dest: "{{ pycharm_tmp_dir.path }}/pycharm.tar.gz"

- name: Unpack install archive
  unarchive:
    src: "{{ pycharm_tmp_dir.path }}/pycharm.tar.gz"
    dest: ~
    list_files: yes
  register: pycharm_unarchive

- name: Install JetBrains Toolbox
  command: "./{{ pycharm_unarchive.files | first }}pycharm"