---
- name: Add Repository for Microsoft VS CODE
  yum_repository:
    name: code
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: yes
    
- name: Update GNOME softwares
  dnf: 
    name: ['gnome-tweak-tool', 'gnome-todo', 'gnome-music']
    state: present

- name: Install visual studio code
  dnf: 
    name: code
    state: latest